name: Build Master
    
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: mathe-vorkurs.tex
      - uses: actions/upload-artifact@v2
        with:
            name: mathe-vorkurs
            path: mathe-vorkurs.pdf

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: mathe-vorkurs
    - run: |
        pwd
        ls -l
        sudo apt-get install davfs2
        sudo mkdir /mnt/dav
        sudo mount -t davfs -o noexec https://syncandshare.lrz.de/webdav /mnt/dav/
        ls -l /mnt/dav
