name: Build Master
    
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls chapters/*.tex | awk '{printf "\\input{%s}\n", $1}' > _chapters.tex
      - name: Install LaTeX build environment
        run: |
          sudo apt-get install texlive texlive-latex-recommended texlive-latex-extra texlive-bibtexextra
      - name: Build LaTeX document
        run: |
          latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode mathe-vorkurs.tex
      - uses: actions/upload-artifact@v2
        with:
            name: mathe-vorkurs
            path: mathe-vorkurs.pdf

  publish-sync-and-share:
    runs-on: ubuntu-latest
    needs: build
    env:
      SAS_USER: ${{ secrets.SYNC_AND_SHARE_USER }}
      SAS_PASS: ${{ secrets.SYNC_AND_SHARE_PASS }}
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: mathe-vorkurs
    - name: Upload to Sync+Share
      run: |
        sudo apt-get install davfs2
        echo "https://syncandshare.lrz.de/webdav" "$SAS_USER" "$SAS_PASS" | sudo tee -a /etc/davfs2/secrets
        mkdir dav
        sudo mount -t davfs -o rw,user,noexec,uid=$USER https://syncandshare.lrz.de/webdav ./dav/
        ls -l dav/ei-erstsemester/vorlesungen/mathe-vorkurs/loesungen-KEINE-GARANTIE/
        cp mathe-vorkurs.pdf dav/ei-erstsemester/vorlesungen/mathe-vorkurs/loesungen-KEINE-GARANTIE/.
        
  publish-discord:
    runs-on: ubuntu-latest
    needs: build
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_GUILD: ${{ secrets.DISCORD_GUILD }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: mathe-vorkurs
    - name: Upload to Discord
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install -U discord.py
        python3 .github/workflows/upload-discord.py
