name: Build Master
    
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: mathe-vorkurs.tex
      - uses: actions/upload-artifact@v2
        with:
            name: mathe-vorkurs
            path: mathe-vorkurs.pdf

  publish:
    runs-on: ubuntu-latest
    needs: build
    env:
      SAS_USER: ${{ secrets.SYNC_AND_SHARE_USER }}
      SAS_PASS: ${{ secrets.SYNC_AND_SHARE_PASS }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_GUILD: ${{ secrets.DISCORD_GUILD }}
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: mathe-vorkurs
    - run: |
        sudo mkdir -p /etc/davfs2/
        sudo touch /etc/davfs2/secrets
        echo "https://syncandshare.lrz.de/webdav" "$SAS_USER" "$SAS_PASS" | sudo tee -a /etc/davfs2/secrets
        sudo chmod 600 /etc/davfs2/secrets
        sudo apt-get install davfs2
        mkdir dav
        sudo mount -t davfs -o rw,user,noexec,uid=$USER https://syncandshare.lrz.de/webdav ./dav/
        ls -l dav
        ls -l dav/*
        cp mathe-vorkurs.pdf dav/mathe-vorkurs/loesungen-KEINE-GARANTIE/.
