name: Build Master
    
on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_GUILD: ${{ secrets.DISCORD_GUILD }}
    steps:
      - uses: actions/checkout@v2
      - name: Install build environment
        run: |
          sudo apt-get install texlive texlive-latex-recommended texlive-latex-extra texlive-bibtex-extra latexmk biber
      - name: Set up build
        run: |
          ls chapters/*.tex | awk '{printf "\\input{%s}\n", $1}' > _chapters.tex
      - name: Build LaTeX document
        run: |
          latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode mathe-vorkurs.tex
      - uses: actions/upload-artifact@v2
        with:
          name: mathe-vorkurs
          path: mathe-vorkurs.pdf
      - name: Upload to Discord
        continue-on-error: true
        run: |
          sudo apt-get install python3-setuptools
          python3 -m pip install -U discord.py
          python3 .github/workflows/upload-discord.py
